import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { SwappableTable } from "../components/elements/SwappableTable/SwappableTable";

import { Users } from "../components/pages/Users/Users";
import { Matching } from "../components/pages/Matching/Matching";

import { Tab, Tabs, TabList, TabPanel } from 'react-tabs';
import 'react-tabs/style/react-tabs.css';

const Home: NextPage = () => {

  const data = {
    columns: [
      { id: "0", value: "0" },
      { id: "1", value: "1" },
      { id: "2", value: "2" },
      { id: "3", value: "3" },
      { id: "4", value: "4" },
      { id: "5", value: "5" },
      { id: "6", value: "6" },
      { id: "7", value: "7" },
      { id: "8", value: "8" },
      { id: "9", value: "9" },
    ]
  };

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>   

      <Tabs>
        <TabList>
          <Tab>Users</Tab>
          <Tab>Matching</Tab>
        </TabList>

        <TabPanel>
          <Users {...data} />
        </TabPanel>
        <TabPanel>
          <Matching {...data} />
        </TabPanel>
      </Tabs>        
    </>
  )
}

export default Home
